//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer_response
    {
        public int page { get; set; }
        public int pageSize { get; set; }
        public string searchTerm { get; set; }
        public int id { get; set; }
        public int surveyID { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_nguoi_hoc_khao_sat { get; set; }
        public string email { get; set; }
        public string json_answer { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> id_namhoc { get; set; }
    
        public virtual NamHoc NamHoc { get; set; }
        public virtual nguoi_hoc_khao_sat nguoi_hoc_khao_sat { get; set; }
        public virtual survey survey { get; set; }
        public virtual users users { get; set; }
    }
}
