//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_cau_hoi_tieu_de
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chi_tiet_cau_hoi_tieu_de()
        {
            this.dieu_kien_cau_hoi = new HashSet<dieu_kien_cau_hoi>();
            this.radio_cau_hoi_khac = new HashSet<radio_cau_hoi_khac>();
        }
    
        public int id_chi_tiet_cau_hoi_tieu_de { get; set; }
        public Nullable<int> thu_tu { get; set; }
        public Nullable<int> id_tieu_de_phieu { get; set; }
        public string ten_cau_hoi { get; set; }
        public Nullable<int> id_dang_cau_hoi { get; set; }
        public Nullable<int> bat_buoc { get; set; }
        public Nullable<int> is_ykienkhac { get; set; }
        public string dieu_kien_hien_thi { get; set; }
    
        public virtual dang_cau_hoi dang_cau_hoi { get; set; }
        public virtual tieu_de_phieu_khao_sat tieu_de_phieu_khao_sat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dieu_kien_cau_hoi> dieu_kien_cau_hoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radio_cau_hoi_khac> radio_cau_hoi_khac { get; set; }
    }
}
