//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuc_nang_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chuc_nang_users()
        {
            this.phan_quyen_chuc_nang_users = new HashSet<phan_quyen_chuc_nang_users>();
        }
    
        public int id_chuc_nang { get; set; }
        public string ten_chuc_nang { get; set; }
        public string ma_chuc_nang { get; set; }
        public Nullable<int> id_typeusers { get; set; }
        public string ghi_chu { get; set; }
    
        public virtual typeusers typeusers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phan_quyen_chuc_nang_users> phan_quyen_chuc_nang_users { get; set; }
    }
}
