//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSurveyEntities : DbContext
    {
        public dbSurveyEntities()
            : base("name=dbSurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer_response> answer_response { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<bo_mon> bo_mon { get; set; }
        public virtual DbSet<chi_tiet_cau_hoi_tieu_de> chi_tiet_cau_hoi_tieu_de { get; set; }
        public virtual DbSet<chuc_nang_users> chuc_nang_users { get; set; }
        public virtual DbSet<ctdt> ctdt { get; set; }
        public virtual DbSet<dang_cau_hoi> dang_cau_hoi { get; set; }
        public virtual DbSet<dieu_kien_cau_hoi> dieu_kien_cau_hoi { get; set; }
        public virtual DbSet<dot_khao_sat> dot_khao_sat { get; set; }
        public virtual DbSet<group_loaikhaosat> group_loaikhaosat { get; set; }
        public virtual DbSet<hedaotao> hedaotao { get; set; }
        public virtual DbSet<khoa_children> khoa_children { get; set; }
        public virtual DbSet<khoa_vien_truong> khoa_vien_truong { get; set; }
        public virtual DbSet<LoaiKhaoSat> LoaiKhaoSat { get; set; }
        public virtual DbSet<log_time_extension_survey> log_time_extension_survey { get; set; }
        public virtual DbSet<lop> lop { get; set; }
        public virtual DbSet<MailAttachments> MailAttachments { get; set; }
        public virtual DbSet<MailLogs> MailLogs { get; set; }
        public virtual DbSet<MailRecipients> MailRecipients { get; set; }
        public virtual DbSet<NamHoc> NamHoc { get; set; }
        public virtual DbSet<NavBar> NavBar { get; set; }
        public virtual DbSet<nguoi_hoc_khao_sat> nguoi_hoc_khao_sat { get; set; }
        public virtual DbSet<phan_quyen_chuc_nang_users> phan_quyen_chuc_nang_users { get; set; }
        public virtual DbSet<phan_quyen_users> phan_quyen_users { get; set; }
        public virtual DbSet<radio_cau_hoi_khac> radio_cau_hoi_khac { get; set; }
        public virtual DbSet<sinhvien> sinhvien { get; set; }
        public virtual DbSet<survey> survey { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tieu_de_phieu_khao_sat> tieu_de_phieu_khao_sat { get; set; }
        public virtual DbSet<typeusers> typeusers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
