//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ctdt()
        {
            this.lop = new HashSet<lop>();
            this.phan_quyen_users = new HashSet<phan_quyen_users>();
        }
    
        public int id_ctdt { get; set; }
        public string ma_ctdt { get; set; }
        public string ten_ctdt { get; set; }
        public Nullable<int> id_bo_mon { get; set; }
        public Nullable<int> id_khoa_children { get; set; }
        public Nullable<int> id_khoa_vien_truong { get; set; }
        public Nullable<int> id_hdt { get; set; }
        public int ngaycapnhat { get; set; }
        public int ngaytao { get; set; }
    
        public virtual bo_mon bo_mon { get; set; }
        public virtual hedaotao hedaotao { get; set; }
        public virtual khoa_children khoa_children { get; set; }
        public virtual khoa_vien_truong khoa_vien_truong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lop> lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phan_quyen_users> phan_quyen_users { get; set; }
    }
}
