//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dieu_kien_cau_hoi
    {
        public int id_cau_hoi_dieu_kien_khac { get; set; }
        public Nullable<int> id_chi_tiet_tieu_de_cau_hoi { get; set; }
        public Nullable<int> id_rd_chk { get; set; }
        public string json_question { get; set; }
    
        public virtual chi_tiet_cau_hoi_tieu_de chi_tiet_cau_hoi_tieu_de { get; set; }
        public virtual radio_cau_hoi_khac radio_cau_hoi_khac { get; set; }
    }
}
