//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khoa_vien_truong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khoa_vien_truong()
        {
            this.bo_mon = new HashSet<bo_mon>();
            this.ctdt = new HashSet<ctdt>();
            this.khoa_children = new HashSet<khoa_children>();
            this.phan_quyen_users = new HashSet<phan_quyen_users>();
        }
    
        public int id_khoa { get; set; }
        public string ma_khoa { get; set; }
        public string ten_khoa { get; set; }
        public Nullable<int> id_namhoc { get; set; }
        public Nullable<int> is_chuyen_mon { get; set; }
        public int ngaycapnhat { get; set; }
        public int ngaytao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bo_mon> bo_mon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdt> ctdt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<khoa_children> khoa_children { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phan_quyen_users> phan_quyen_users { get; set; }
    }
}
