//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKhaoSat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiKhaoSat()
        {
            this.survey = new HashSet<survey>();
        }
    
        public int id_loaikhaosat { get; set; }
        public string name_loaikhaosat { get; set; }
        public Nullable<int> id_gr_loaikhaosat { get; set; }
        public Nullable<int> TimeMake { get; set; }
        public Nullable<int> TimeUpdate { get; set; }
    
        public virtual group_loaikhaosat group_loaikhaosat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey> survey { get; set; }
    }
}
