//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_time_extension_survey
    {
        public int id_log_time_extension { get; set; }
        public Nullable<int> time_log_start { get; set; }
        public Nullable<int> time_log_end { get; set; }
        public Nullable<int> surveyid { get; set; }
    
        public virtual survey survey { get; set; }
    }
}
