//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailAttachments
    {
        public int id_mail_attachments { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<int> id_mail_logs { get; set; }
    
        public virtual MailLogs MailLogs { get; set; }
    }
}
