//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavBar
    {
        public int id_navbar { get; set; }
        public Nullable<int> thu_tu_hien_thi { get; set; }
        public string name_navbar { get; set; }
        public string link_navbar { get; set; }
        public Nullable<int> is_open { get; set; }
    }
}
