//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_hoc_khao_sat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoi_hoc_khao_sat()
        {
            this.answer_response = new HashSet<answer_response>();
        }
    
        public int id_nguoi_hoc_khao_sat { get; set; }
        public int surveyID { get; set; }
        public int id_sv { get; set; }
        public int is_khao_sat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_response> answer_response { get; set; }
        public virtual sinhvien sinhvien { get; set; }
        public virtual survey survey { get; set; }
    }
}
