//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phan_quyen_chuc_nang_users
    {
        public int id_phan_quyen { get; set; }
        public int id_users { get; set; }
        public int id_chuc_nang { get; set; }
    
        public virtual chuc_nang_users chuc_nang_users { get; set; }
        public virtual users users { get; set; }
    }
}
