//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phan_quyen_users
    {
        public int id_phan_quyen_user { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_ctdt { get; set; }
        public Nullable<int> id_don_vi { get; set; }
        public Nullable<int> id_khoa { get; set; }
        public Nullable<int> id_bo_mon { get; set; }
    
        public virtual bo_mon bo_mon { get; set; }
        public virtual ctdt ctdt { get; set; }
        public virtual khoa_children khoa_children { get; set; }
        public virtual khoa_vien_truong khoa_vien_truong { get; set; }
        public virtual users users { get; set; }
    }
}
