//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class radio_cau_hoi_khac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public radio_cau_hoi_khac()
        {
            this.dieu_kien_cau_hoi = new HashSet<dieu_kien_cau_hoi>();
        }
    
        public int id_rd_cau_hoi_khac { get; set; }
        public Nullable<int> thu_tu { get; set; }
        public string ten_rd_cau_hoi_khac { get; set; }
        public Nullable<int> id_chi_tiet_cau_hoi_tieu_de { get; set; }
    
        public virtual chi_tiet_cau_hoi_tieu_de chi_tiet_cau_hoi_tieu_de { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dieu_kien_cau_hoi> dieu_kien_cau_hoi { get; set; }
    }
}
