//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public survey()
        {
            this.answer_response = new HashSet<answer_response>();
            this.log_time_extension_survey = new HashSet<log_time_extension_survey>();
            this.nguoi_hoc_khao_sat = new HashSet<nguoi_hoc_khao_sat>();
            this.tieu_de_phieu_khao_sat = new HashSet<tieu_de_phieu_khao_sat>();
        }
        public int page { get; set; }
        public int pageSize { get; set; }
        public string searchTerm { get; set; }
        public int surveyID { get; set; }
        public Nullable<int> id_hedaotao { get; set; }
        public string surveyData { get; set; }
        public string surveyTitle { get; set; }
        public string surveyDescription { get; set; }
        public Nullable<int> surveyTimeStart { get; set; }
        public Nullable<int> surveyTimeEnd { get; set; }
        public Nullable<int> surveyTimeMake { get; set; }
        public Nullable<int> surveyTimeUpdate { get; set; }
        public Nullable<int> surveyStatus { get; set; }
        public int id_loaikhaosat { get; set; }
        public Nullable<int> creator { get; set; }
        public Nullable<int> id_namhoc { get; set; }
        public Nullable<int> id_dot_khao_sat { get; set; }
        public Nullable<int> mo_thong_ke { get; set; }
        public string ty_le_phan_tram_dat { get; set; }
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_response> answer_response { get; set; }
        public virtual dot_khao_sat dot_khao_sat { get; set; }
        public virtual hedaotao hedaotao { get; set; }
        public virtual LoaiKhaoSat LoaiKhaoSat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log_time_extension_survey> log_time_extension_survey { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nguoi_hoc_khao_sat> nguoi_hoc_khao_sat { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tieu_de_phieu_khao_sat> tieu_de_phieu_khao_sat { get; set; }
    }
}
