//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tieu_de_phieu_khao_sat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tieu_de_phieu_khao_sat()
        {
            this.chi_tiet_cau_hoi_tieu_de = new HashSet<chi_tiet_cau_hoi_tieu_de>();
        }
        public string sortType { get; set; }
        public int id_tieu_de_phieu { get; set; }
        public string thu_tu { get; set; }
        public Nullable<int> thu_tu_sap_xep { get; set; }
        public Nullable<int> surveyID { get; set; }
        public string ten_tieu_de { get; set; }
        public string desception { get; set; }
        public string dieu_kien_hien_thi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_cau_hoi_tieu_de> chi_tiet_cau_hoi_tieu_de { get; set; }
        public virtual survey survey { get; set; }
    }
}
